issues:
  - label: "bug"
    items:
      - description: "å†…å®¹ç¼ºå¤±"
        content:
          - "å†…å®¹1"
          - "å†…å®¹2"
      - description: "ç¼ºå°‘ğŸ¶"
        content:
          - "ğŸ¶"
  - label: "Feature Request"
    items:
      - description: "ç¼ºå°‘ğŸ±"
        content:
          - "ğŸ±"
comment: "test"